In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

file_path = 'data/imdb_top_1000.csv'

df_raw = pd.read_csv(file_path)

#print(df_raw['Certificate'].unique())

rating_age_map = {
    'A': 18, 'U': 0, 'UA': 7, 'U/A': 7, 'PG': 8, 'PG-13': 13, 'R': 17, 'G': 0, 'Passed': 0, 'Approved': 0, 
    'GP': 10, 'TV-14': 14, 'TV-MA': 17, 'TV-PG': 10, '16': 16, 'Unrated': None, 'NaN': None       
}
df_raw['Certificate'] = df_raw['Certificate'].map(rating_age_map)

df_raw['Runtime'] = df_raw['Runtime'].str.extract('(\d+)').astype(int)
df_raw['Genre'] = df_raw['Genre'].str.split(', ')

tfidf = TfidfVectorizer(stop_words='english')
df_raw['overview_tfidf'] = list(tfidf.fit_transform(df_raw['Overview']).toarray())

encoder = OneHotEncoder()
directors_encoded = encoder.fit_transform(df_raw[['Director']])

#print(directors_encoded)

df_raw

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,overview_tfidf
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,18.0,142,[Drama],9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,18.0,175,"[Crime, Drama]",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,7.0,152,"[Action, Crime, Drama]",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,18.0,202,"[Crime, Drama]",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,0.0,96,"[Crime, Drama]",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,18.0,115,"[Comedy, Drama, Romance]",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,0.0,201,"[Drama, Western]",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,0.0,118,"[Drama, Romance, War]",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97,"[Drama, War]",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86,"[Crime, Mystery, Thriller]",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [39]:
import pandas as pd

# dictionary to specify replacement values based on data type
replacement_values = {}

for column in df_raw.columns:
    # Determine the data type of the column
    column_dtype = df_raw[column].dtype
    
    # Set the replacement value based on the data type
    if pd.api.types.is_numeric_dtype(column_dtype):
        # Numeric column (int or float)
        replacement_values[column] = 0.0  # Use 0.0 for float columns
    else:
        # Non-numeric column (object or string)
        replacement_values[column] = 0  # Use 0 for integer or string columns

# Replace NaN values with the specified replacement values
df_raw.fillna(replacement_values, inplace=True)

# Display the updated DataFrame
print(df_raw)

                                           Poster_Link  \
0    https://m.media-amazon.com/images/M/MV5BMDFkYT...
1    https://m.media-amazon.com/images/M/MV5BM2MyNj...
2    https://m.media-amazon.com/images/M/MV5BMTMxNT...
3    https://m.media-amazon.com/images/M/MV5BMWMwMG...
4    https://m.media-amazon.com/images/M/MV5BMWU4N2...
..                                                 ...
995  https://m.media-amazon.com/images/M/MV5BNGEwMT...
996  https://m.media-amazon.com/images/M/MV5BODk3Yj...
997  https://m.media-amazon.com/images/M/MV5BM2U3Yz...
998  https://m.media-amazon.com/images/M/MV5BZTBmMj...
999  https://m.media-amazon.com/images/M/MV5BMTY5OD...

                 Series_Title Released_Year  Certificate  Runtime  \
0    The Shawshank Redemption          1994         18.0      142
1               The Godfather          1972         18.0      175
2             The Dark Knight          2008          7.0      152
3      The Godfather: Part II          1974         18.0      202
4                12 Angry Men          1957          0.0       96
..                        ...           ...          ...      ...
995    Breakfast at Tiffany's          1961         18.0      115
996                     Giant          1956          0.0      201
997     From Here to Eternity          1953          0.0      118
998                  Lifeboat          1944          0.0       97
999              The 39 Steps          1935          0.0       86

                          Genre  IMDB_Rating  \
0                       [Drama]          9.3
1                [Crime, Drama]          9.2
2        [Action, Crime, Drama]          9.0
3                [Crime, Drama]          9.0
4                [Crime, Drama]          9.0
..                          ...          ...
995    [Comedy, Drama, Romance]          7.6
996            [Drama, Western]          7.6
997       [Drama, Romance, War]          7.6
998                [Drama, War]          7.6
999  [Crime, Mystery, Thriller]          7.6

                                              Overview  Meta_score  \
0    Two imprisoned men bond over a number of years...        80.0
1    An organized crime dynasty's aging patriarch t...       100.0
2    When the menace known as the Joker wreaks havo...        84.0
3    The early life and career of Vito Corleone in ...        90.0
4    A jury holdout attempts to prevent a miscarria...        96.0
..                                                 ...         ...
995  A young New York socialite becomes interested ...        76.0
996  Sprawling epic covering the life of a Texas ca...        84.0
997  In Hawaii in 1941, a private is cruelly punish...        85.0
998  Several survivors of a torpedoed merchant ship...        78.0
999  A man in London tries to help a counter-espion...        93.0

                 Director              Star1              Star2  \
0          Frank Darabont        Tim Robbins     Morgan Freeman
1    Francis Ford Coppola      Marlon Brando          Al Pacino
2       Christopher Nolan     Christian Bale       Heath Ledger
3    Francis Ford Coppola          Al Pacino     Robert De Niro
4            Sidney Lumet        Henry Fonda        Lee J. Cobb
..                    ...                ...                ...
995         Blake Edwards     Audrey Hepburn     George Peppard
996        George Stevens   Elizabeth Taylor        Rock Hudson
997        Fred Zinnemann     Burt Lancaster   Montgomery Clift
998      Alfred Hitchcock  Tallulah Bankhead        John Hodiak
999      Alfred Hitchcock       Robert Donat  Madeleine Carroll

              Star3           Star4  No_of_Votes        Gross  \
0        Bob Gunton  William Sadler      2343110   28,341,469
1        James Caan    Diane Keaton      1620367  134,966,411
2     Aaron Eckhart   Michael Caine      2303232  534,858,444
3     Robert Duvall    Diane Keaton      1129952   57,300,000
4     Martin Balsam    John Fiedler       689845    4,360,000
..              ...             ...          ...          ...
995   Patricia Neal     Buddy Ebsen       166544            0
996      James Dean   Carroll Baker        34075            0
997    Deborah Kerr      Donna Reed        43374   30,500,000
998   Walter Slezak  William Bendix        26471            0
999  Lucie Mannheim  Godfrey Tearle        51853            0

                                        overview_tfidf
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
..                                                 ...
995  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
996  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
997  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
998  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
999  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

[1000 rows x 17 columns]

In [40]:
from sklearn.preprocessing import MultiLabelBinarizer

# Convert Genre into a list of genres (assuming it's already split into lists)
mlb = MultiLabelBinarizer()
genre_encoded = pd.DataFrame(mlb.fit_transform(df_raw['Genre']), columns=mlb.classes_, index=df_raw.index)

# Concatenate the one-hot encoded genre features with the original DataFrame
df_raw = pd.concat([df_raw, genre_encoded], axis=1)

df_raw

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,...,Horror,Music,Musical,Mystery,Romance,Sci-Fi,Sport,Thriller,War,Western
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,18.0,142,[Drama],9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,...,0,0,0,0,0,0,0,0,0,0
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,18.0,175,"[Crime, Drama]",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,...,0,0,0,0,0,0,0,0,0,0
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,7.0,152,"[Action, Crime, Drama]",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,...,0,0,0,0,0,0,0,0,0,0
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,18.0,202,"[Crime, Drama]",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,...,0,0,0,0,0,0,0,0,0,0
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,0.0,96,"[Crime, Drama]",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,18.0,115,"[Comedy, Drama, Romance]",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,...,0,0,0,0,1,0,0,0,0,0
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,0.0,201,"[Drama, Western]",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,...,0,0,0,0,0,0,0,0,0,1
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,0.0,118,"[Drama, Romance, War]",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,...,0,0,0,0,1,0,0,0,1,0
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,0.0,97,"[Drama, War]",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,...,0,0,0,0,0,0,0,0,1,0
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,0.0,86,"[Crime, Mystery, Thriller]",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,...,0,0,0,1,0,0,0,1,0,0

In [41]:
from sklearn.preprocessing import OneHotEncoder

# Initialize OneHotEncoder
encoder = OneHotEncoder()

# Fit and transform the Director feature into one-hot encoded vectors
directors_encoded = encoder.fit_transform(df_raw[['Director']])

# Convert the sparse matrix into a DataFrame and concatenate with the original DataFrame
directors_encoded_df = pd.DataFrame(directors_encoded.toarray(), columns=encoder.get_feature_names_out(), index=df_raw.index)
df_raw = pd.concat([df_raw, directors_encoded_df], axis=1)

df_raw

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,...,Director_Yilmaz Erdogan,Director_Yimou Zhang,Director_Yoshiaki Kawajiri,Director_Yoshifumi Kondô,Director_Yôjirô Takita,Director_Zack Snyder,Director_Zaza Urushadze,Director_Zoya Akhtar,Director_Çagan Irmak,Director_Ömer Faruk Sorak
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,18.0,142,[Drama],9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,18.0,175,"[Crime, Drama]",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,7.0,152,"[Action, Crime, Drama]",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,18.0,202,"[Crime, Drama]",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,0.0,96,"[Crime, Drama]",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,18.0,115,"[Comedy, Drama, Romance]",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,0.0,201,"[Drama, Western]",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,0.0,118,"[Drama, Romance, War]",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,0.0,97,"[Drama, War]",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,0.0,86,"[Crime, Mystery, Thriller]",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [42]:
df_raw['Gross'] = df_raw['Gross'].replace(',', '', regex=True).astype(float)

print(df_raw['Gross'])

0       28341469.0
1      134966411.0
2      534858444.0
3       57300000.0
4        4360000.0
          ...
995            0.0
996            0.0
997     30500000.0
998            0.0
999            0.0
Name: Gross, Length: 1000, dtype: float64

In [43]:
print(df_raw["Gross"])

0       28341469.0
1      134966411.0
2      534858444.0
3       57300000.0
4        4360000.0
          ...
995            0.0
996            0.0
997     30500000.0
998            0.0
999            0.0
Name: Gross, Length: 1000, dtype: float64

In [44]:

numeric_columns = ['Runtime', 'Gross', 'Released_Year', 'IMDB_Rating', 'Meta_score']

# Convert selected columns to numeric type (if not already)
df_raw[numeric_columns] = df_raw[numeric_columns].apply(pd.to_numeric, errors='coerce')

# Calculate the maximum and minimum values for each numeric column
max_values = df_raw[numeric_columns].max()
min_values = df_raw[numeric_columns].min()

# Display the maximum and minimum values for each column
print("Maximum values:")
print(max_values)
print("\nMinimum values:")
print(min_values)

Maximum values:
Runtime                321.0
Gross            936662225.0
Released_Year         2020.0
IMDB_Rating              9.3
Meta_score             100.0
dtype: float64

Minimum values:
Runtime            45.0
Gross               0.0
Released_Year    1920.0
IMDB_Rating         7.6
Meta_score          0.0
dtype: float64

In [54]:
import pandas as pd
import numpy as np 

# Define maximum and minimum values for numeric features
max_values = {
    'Runtime': 321.0,
    'Released_Year': 2020.0,
    'IMDB_Rating': 9.3,
    'Meta_score': 100.0
}

min_values = {
    'Runtime': 45.0,
    'Released_Year': 1920.0,
    'IMDB_Rating': 7.6,
    'Meta_score': 0.0
}


numeric_columns = ['Runtime', 'Released_Year', 'IMDB_Rating', 'Meta_score']
df_raw[numeric_columns] = df_raw[numeric_columns].apply(pd.to_numeric, errors='coerce')

# Define the scaling factor (k)
k = 0.5  # Adjust this based on the sensitivity you want

# Function to calculate similarity based on numeric difference and scaling factor (k)
def calculate_similarity(x, y, feature_name):
    max_val = max_values[feature_name]
    min_val = min_values[feature_name]
    range_val = max_val - min_val
    
    # Handle missing or invalid values
    if np.isnan(x) or np.isnan(y) or range_val == 0:
        return 0.0  # Return 0 similarity for missing or invalid values
    
    difference = abs(x - y)
    similarity = max(100 - k * (difference / range_val) * 100, 0)
    return similarity

# Example usage:
movie1 = df_raw.iloc[0]  # Example movie 1 (choose a specific row)
movie2 = df_raw.iloc[4]  # Example movie 2 (choose another specific row)

# Calculate similarity based on different numeric features
similarity_runtime = calculate_similarity(movie1['Runtime'], movie2['Runtime'], 'Runtime')
similarity_year = calculate_similarity(movie1['Released_Year'], movie2['Released_Year'], 'Released_Year')
similarity_imdb = calculate_similarity(movie1['IMDB_Rating'], movie2['IMDB_Rating'], 'IMDB_Rating')
similarity_metascore = calculate_similarity(movie1['Meta_score'], movie2['Meta_score'], 'Meta_score')

# Print similarity scores
print(f"Similarity (Runtime): {similarity_runtime:.2f}")
print(f"Similarity (Released Year): {similarity_year:.2f}")
print(f"Similarity (IMDB Rating): {similarity_imdb:.2f}")
print(f"Similarity (Metascore): {similarity_metascore:.2f}")

Similarity (Runtime): 91.67
Similarity (Released Year): 81.50
Similarity (IMDB Rating): 91.18
Similarity (Metascore): 92.00

In [55]:
import pandas as pd
import numpy as np 

# Define maximum and minimum values for numeric features
max_values = {
    'Runtime': 321.0,
    'Released_Year': 2020.0,
    'IMDB_Rating': 9.3,
    'Meta_score': 100.0
}

min_values = {
    'Runtime': 45.0,
    'Released_Year': 1920.0,
    'IMDB_Rating': 7.6,
    'Meta_score': 0.0
}

# Function to calculate similarity based on numeric difference and custom scaling factor (k)
def calculate_similarity(x, y, feature_name, k):
    max_val = max_values[feature_name]
    min_val = min_values[feature_name]
    range_val = max_val - min_val
    
    # Handle missing or invalid values
    if pd.isnull(x) or pd.isnull(y) or range_val == 0:
        return 0.0  # Return 0 similarity for missing or invalid values
    
    difference = abs(x - y)
    similarity = max(100 - k * (difference / range_val) * 100, 0)
    
    # Normalize similarity between 0 and 1
    similarity_normalized = similarity / 100.0
    return similarity_normalized

# Example usage with customizable scaling factors (k) for each numeric feature
def test_similarity():
    file_path = 'data/imdb_top_1000.csv'
    df_raw = pd.read_csv(file_path)

    # Convert selected columns to numeric types
    numeric_columns = ['Released_Year', 'IMDB_Rating', 'Meta_score']
    df_raw[numeric_columns] = df_raw[numeric_columns].apply(pd.to_numeric, errors='coerce')

    # Example movie indices
    movie1_index = 0
    movie2_index = 1

    # Select movies based on indices
    movie1 = df_raw.iloc[movie1_index]
    movie2 = df_raw.iloc[movie2_index]

    # Define scaling factors (k) for each numeric feature
    k_year = 0.7
    k_imdb = 0.4
    k_metascore = 0.6

    # Calculate similarity based on different numeric features with custom scaling factors (k)
    similarity_year = calculate_similarity(movie1['Released_Year'], movie2['Released_Year'], 'Released_Year', k_year)
    similarity_imdb = calculate_similarity(movie1['IMDB_Rating'], movie2['IMDB_Rating'], 'IMDB_Rating', k_imdb)
    similarity_metascore = calculate_similarity(movie1['Meta_score'], movie2['Meta_score'], 'Meta_score', k_metascore)

    # Print similarity scores as decimal values between 0 and 1
    print(f"Similarity (Released Year): {similarity_year:.4f}")
    print(f"Similarity (IMDB Rating): {similarity_imdb:.4f}")
    print(f"Similarity (Metascore): {similarity_metascore:.4f}")

# Call the function to test similarity calculation
test_similarity()

Similarity (Released Year): 0.8460
Similarity (IMDB Rating): 0.9765
Similarity (Metascore): 0.8800